steps:
  # Run unit tests
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install -r requirements.txt && pytest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
